import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LoaderWrapper from "src/@core/components/LoaderWrapper";
import {
  AppContextProvider,
  AppContextWrapper,
} from "src/@core/context/AppContext";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoaderWrapper>
          <AppContextProvider>
            <AppContextWrapper>
              <Suspense fallback={<>loading</>}>{children}</Suspense>
            </AppContextWrapper>
          </AppContextProvider>
        </LoaderWrapper>
      </body>
    </html>
  );
}
